### ISSUE TITLE
Error:Execution failed for task ':app:processDebugManifest'. 

### ISSUE THREAD

**Issue by GreeNxGit** [NHTuan10/IMApp#1]
Em mở app thì bị lỗi này, phải sửa sao anh?

**Comment by NHTuan10** [comment]
Hello hoangcuongdev,
Thank you for pointing out this error. It's better if you could provide the full-stack trace here, so I can find out which causes the issue faster. Actually, I had no issue when I built the app on my local machine. 

So, did you build the app with Android SDK 23 and build tool 23.0.2 ? I ask this because the app may not work with some version.
