### ISSUE TITLE
login app

### ISSUE THREAD

**Issue by GreeNxGit** [NHTuan10/IMApp#2]
i cant't login App when using Server xmpp Openfire on Vmware?

**Comment by NHTuan10** [comment]
Hello  hoangcuongdev,

Thank you very much for pointing out the issue. 
If the issue is caused by incorrect server address configuration, please modify the string resources "server_address" and "port" in file: https://github.com/NHTuan10/IMApp/blob/master/IMApp/app/src/main/res/values/strings.xml  
with your server address and port. 

If not, please give me the full stack trace of the error, so we can troubleshoot the problem.

Thank you,
Tuan
